apiVersion: v1
kind: Service
metadata:
    name: coordinator-service
    namespace: applications-namespace
spec:
    type: LoadBalancer
    selector:
        app: coordinator
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
