apiVersion: v1
kind: Service
metadata:
    name: pool-manager-service
    namespace: applications-namespace
spec:
    type: LoadBalancer
    selector:
        app: pool-manager
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
