apiVersion: v1
kind: Namespace
metadata:
    name: redis-namespace
---
apiVersion: v1
kind: Namespace
metadata:
    name: rabbitmq-namespace
---
apiVersion: v1
kind: Namespace
metadata:
    name: applications-namespace
